### ISSUE TITLE
Coming up with project ideas

### ISSUE THREAD

**Issue by Flbierman** [KTFBP/Project#1]

**Comment by tpark2** [comment]
"Idea pitched to me by insane father in law, A game about squirrels trying to cross the road and live their lives. Squirrel sim .... no bad ideas, my kids seem delighted by the idea.
Simple system of tracking an actors current task, time to task completion, and some random numbers for events with visualization.".........I like the idea from Peter about the squirrel.  It's like a combination of the project examples provided by the professor.
